#!/bin/bash
server=$PWD
cd $server
set -e
chmod +x *
mkdir mcserver

#Installing Variables
sudo apt update
sudo apt-get install -y -qq wget screen default-jdk ssh unzip python3.9

# Install Bpytop
python3 -m pip install bpytop

clear

# Choose Server
echo "Please Choose what Server that you want to Install :"
echo "Type [1] for Minecraft Java Server"
echo "Type [2] for Minecraft Bedrock Server"
selectServer=1
read selectServer

# Install Server
if [[ -z selectServer ]]; then
  echo "Wrong Choice. Please try again"
  clear
  ./setup
#Execute When the User want to Install Java Server

elif [[ -z selectServer == 1 ]]; then
  echo "Installing Minecraft Java Server.."
  wget -O server.jar https://launcher.mojang.com/v1/objects/c8f83c5655308435b3dcf03c06d9fe8740a77469/server.jar
  touch eula.txt
  echo "eula=true" > eula.txt
  mv server.jar mcserver && mv eula.txt mcserver
#Execute When the User want to Install Bedrock Server

elif [[ -z selectServer == 2 ]]; then
  echo "Please Type the Version of Minecraft Bedrock Edition Server that you want :"
  read version
  echo "Installing Minecraft Bedrock Server.."
  wget -O server.zip https://minecraft.azureedge.net/bin-linux/bedrock-server-$version.zip
  touch eula.txt
  echo "eula=true" > eula.txt
  mv server.zip mcserver && mv eula.txt mcserver
  cd mcserver
  unzip server.zip
  cd ..
  cd $server

# Execute when the User doesn't choose any server
else 
  echo "Wrong Choice. Please try again"
  ./setup
fi

wget -O playit https://playit.gg/downloads/playit-0.7.5-beta
chmod +x *
