#!/bin/bash
set -e
export server=$PWD
chmod +x *
cd $server

# Start Java Edition Server
if [ -f $server/mcserver/server.jar ]; then
  cd mcserver
  screen -S Server java -Xmx2G -Xms2G -jar server.jar nogui
# Start Bedrock Edition Server
elif [ -f $server/mcserver/bedrock_server ]; then
  cd mcserver
  chmod +x *
  screen -S Server ./bedrock_server
# It will Setup a Server if You don't have the Server
else 
  echo "You don't have a Minecraft Server Installed. Installing Minecraft Server.."
  ./setup
screen -S stats bpytop
