#!/bin/bash
export server=$PWD
cd $server

echo "Are you sure you want to uninstall your Server?"
echo "Type [1] for 'Yes'"
echo "Type [2] for 'No'"
uninstall=1
read uninstall

# Uninstall
if [[ -z $uninstall ]]; then
  echo "By default, you selected 'No'"
elif [[ $uninstall == 1 ]] then
  echo "Deleting you Server.."
  rm -rf mcserver
  killall screen
  echo "Server deleted! Type ./setup to make a new Server!"
elif [[ $uninstall == 2 ]]; then 
  echo "Server uninstall cancelled!"
